### ISSUE TITLE
Migrate endpoints to V4

### ISSUE THREAD

**Issue by BryanHitchcock** [pseudonym117/Riot-Watcher#106]
Reference: https://discussion.developer.riotgames.com/articles/6579/player-universally-unique-identifiers-and-a-new-se.html

**Comment by GiacomoLaw** [comment]
They are being the 1/28/19, so not too far away. Please update!

Thanks

**Comment by pseudonym117** [comment]
Check branch `v4` which was just pushed. Code is not in a finalized state, so not pushed to `master`.

Basically all that is pending is integration tests for v4, and I still need to manually validate the v4 code. Only usage change is to use v4 instead of v3, use this to create `RiotWatcher` object:

```python
watcher = RiotWatcher('<your-api-key>', v4=True)
```

**Comment by GiacomoLaw** [comment]
Awesome, thanks! I'm using Riotwatcher in my current project, could you let us know when the pip package is updated so I can update?

Thanks for the awesome work!

**Comment by pseudonym117** [comment]
v4 merged and uploaded. 

Please also update any error handling code you happen to have to catch `riotwatcher.ApiError` instead of `requests.HTTPError`. Old `except` __will__ still work this release, but may be removed in future versions.
