### ISSUE TITLE
Missing endpoint: Grandmaster league

### ISSUE THREAD

**Issue by misterpooh** [pseudonym117/Riot-Watcher#107]
Missing Grandmaster league endpoint
/lol/league/v3/grandmasterleagues/by-queue/{queue}

or

 /lol/league/v4/grandmasterleagues/by-queue/{queue} when migrating to v4

**Comment by pseudonym117** [comment]
added in v4 apis in newest package. use constructor `RiotWatcher(api_key, v4=True)` to enable
