### ISSUE TITLE
Positional Ranking Deprecation

### ISSUE THREAD

**Issue by iKevinY** [pseudonym117/Riot-Watcher#117]
Riot's API team [just announced](https://www.riotgames.com/en/DevRel/riot-api-update-190417) that positional ranking endpoints have been deprecated and will be removed on Monday, June 17th, meaning there are changes to the `league-v4` API.

These endpoints are being removed:
- `/lol/league/v4/positional-rank-queues`
- `/lol/league/v4/positions/by-summoner/{encryptedSummonerId}`
- `/lol/league/v4/positions/{positionalQueue}/{tier}/{division}/{position}/{page}`

And these are being added:
- `/lol/league/v4/entries/by-summoner/{encryptedSummonerId}`
- `/lol/league/v4/entries/{queue}/{tier}/{division}`

Unfortunately, I don't currently have the bandwidth to make a PR for this myself, but I hope that by posting this early on, someone will be able to pick up this issue! 😓

**Comment by pseudonym117** [comment]
accidentally closed - code is merged, will be a part of next release on pip. hopefully will be tomorrow, need to do a bit more testing.

**Comment by iKevinY** [comment]
Awesome, thanks for the super-speedy patch! 🎉
