### ISSUE TITLE
API Functions for TFT, LoR, Project A, ...?

### ISSUE THREAD

**Issue by afDeathscythe** [pseudonym117/Riot-Watcher#139]
Hi,

I just wanted to ask you if you plan to provide also the other games APIs like from TFT, LoR, ...?
Would be nice because we plan to implement a general ranking site. :)

Kind Regards,
Marko

**Comment by pseudonym117** [comment]
APIs are added in latest master commit. This package is not yet on PyPi, as I am planning on making a few more changes before this major version is released.

**Comment by afDeathscythe** [comment]
Nice thanks sounds good - if you need an additional contributer do not hesitate to contact me - always glad to help :)

**Comment by pseudonym117** [comment]
New version pushed to PyPi now. New APIs are usable through `LorWatcher` and `TftWatcher` classes
