### ISSUE TITLE
Current Game API

### ISSUE THREAD

**Issue by robotrono** [pseudonym117/Riot-Watcher#14]
when can you put the current game info?

https://developer.riotgames.com/api/methods#!/956
https://developer.riotgames.com/discussion/riot-games-api/show/ji66sYEN

**Comment by pseudonym117** [comment]
What the hell is the point of their change history page if they never
update it for anything? Didn't see that it existed until now. I'll try to
get it in this week, but no promises.

**Comment by robotrono** [comment]
Nice!

**Comment by SonOfASailor** [comment]
Sweet!  I'm looking forward to having a wrapper to get the current match.

**Comment by pseudonym117** [comment]
done. changes committed.
