### ISSUE TITLE
no attribute 'static_data'

### ISSUE THREAD

**Issue by ElPolako** [pseudonym117/Riot-Watcher#147]
Hello,
when I want get 

static_champ_list = lol_watcher.static_data.champions(my_region)

I have error:

> AttributeError: 'LolWatcher' object has no attribute 'static_data'

**Comment by pseudonym117** [comment]
The correct method is `lol_watcher.data_dragon.champions(<game_version_here>)`. Documentation needs to be updated to reflect this...
