### ISSUE TITLE
league.positions_by_summoner Error

### ISSUE THREAD

**Issue by ErickJV** [pseudonym117/Riot-Watcher#151]
AttributeError: 'LeagueApiV4' object has no attribute 'positions_by_summoner'

**Comment by GiacomoLaw** [comment]
Hey there, getting this on the latest version.

https://github.com/GiacomoLaw/leaguestatistics/blob/822de60c738f58dee5211ce43ee82e6b69bc9e05/lib/functions.py#L35

Returns `AttributeError: 'LeagueApiV4' object has no attribute 'positions_by_summoner'`.

Thanks!
