### ISSUE TITLE
get this on pypi

### ISSUE THREAD

**Issue by RyanHope** [pseudonym117/Riot-Watcher#16]
This is a great package. You should take 10 minutes and turn this into a proper package, get it on PyPi so that it can be installed by pip.

**Comment by chenwardT** [comment]
+1

**Comment by pseudonym117** [comment]
honestly, dont know how to do it and dont have time right now to make it one. anyone is welcome to submit it as a pull request, if it works i will add it pretty much right away, but as of now, dont have time to do this. itll be on my radar, but very low priority.

**Comment by RyanHope** [comment]
See pull request 1

**Comment by pseudonym117** [comment]
uploaded. package name is "riotwatcher". thanks to RyanHope for the package.

**Comment by RyanHope** [comment]
Looks like you might have only registered the project on pypi but havent uploaded a release yet. Check this for help https://docs.python.org/3.1/distutils/uploading.html

**Comment by pseudonym117** [comment]
Oops. I'm dumb. Well upload for real when I get to my computer.

**Comment by pseudonym117** [comment]
fixed for realz now. actually uploaded and everything.
