### ISSUE TITLE
filter matchlist_by_account by season - only current season available

### ISSUE THREAD

**Issue by pampicloud** [pseudonym117/Riot-Watcher#168]
hi all
I wrote a program to retrieve all match data of a list of players. This works fine.
A limitation is, that I want to focus on matches only played in season 10.

`matchlist_by_account(region: str, encrypted_account_id: str, queue: Set[str] = None,, **season**: Set[int] = None, champion: Set[int] =None)`

Currently season 10 is up. But I retrieved season 13 as the current season by the loaded matchlist data.
**Are the season IDs not the same as the title of the seasons (1...10)?**

And if I change the season filter to any other number (1-12), no matches are available.
**Is it only possible to retrieve data of the current season?**

**Comment by pseudonym117** [comment]
This is a general limitation of the API, the season flag doesnt really work well, though it does still technically exist. Generally its better to just use the `begin_time` and `end_time` fields, as these work reliably. https://github.com/pseudonym117/Riot-Watcher/blob/master/src/riotwatcher/_apis/league_of_legends/MatchApiV4.py#L40-L41
