### ISSUE TITLE
Match v5 support?

### ISSUE THREAD

**Issue by summonerriftofficial** [pseudonym117/Riot-Watcher#172]
We're making match-v5 available on Development API keys. Production access will follow in the coming weeks/month. We'll be deprecating match-v4 on Monday, June 14th. This begins our typical 60 day deprecation period. https://riot.com/3g7BoEl

**Comment by iaace-NA** [comment]
Asking again since it's been a while: are there any plans to publish the match-v5 changes (even as a nonstable release)?

**Comment by pseudonym117** [comment]
Released as v3.1.2
