### ISSUE TITLE
Error at league_of_legends.MatchApiV4

### ISSUE THREAD

**Issue by JahedulAnowar** [pseudonym117/Riot-Watcher#173]
I tried to get match data:

```
Lol_watcher = LolWatcher(api_key)
match = LolWatcher.match.by_id(region=region, match_id=id)
print(match)
```
i get the following error:
```AttributeError: 'property' object has no attribute 'by_id'```

`matchlist_by_account` and `timeline_by_match` also throws same error.

*version 3.1.1.

**Comment by Gumimaco** [comment]
I did it like this if you didn't find solution as to how to do it.
lol_watcher = LolWatcher("your api key")
match = lol_watcher.match.by_id(my_region, matchId)

**Comment by JahedulAnowar** [comment]
Thank you, that was a mistake from my end.
