### ISSUE TITLE
v5.matchlist_by_puuid returning only one or no result?

### ISSUE THREAD

**Issue by kuhakuna** [pseudonym117/Riot-Watcher#183]
hi, sorry in advance for a probably useless issue, but,

lately I've been trying to grab the last 10 games of my teammates in champ select and snag the win rate from each of those 40 games real fast.

`match_list = league_watcher.match_v5.matchlist_by_puuid(region='AMERICAS', puuid=self.team[i], queue=420, type="ranked", count=10)`
`print(f"match_list:{match_list}")`

output:`match_list:[]`

match_list is either returning 1 game id max for my own puuid, or 0 if I don't specify v5 usage. I don't really understand what I'm doing incorrectly? Sometimes other puuids will return 10 games, but I'm not sure why my own will only return 1 result no matter what I'm giving the server, and I've tried stripping down the params to JUST `queue=420` so I'm really lost here  :( Sorry if there's an obvious document string I missed for this.

**Comment by pseudonym117** [comment]
This was a bug in the API previously. I believe it has since been fixed. Test again and see if it is occurring still. If it is, search here for similar issues, or report new:  https://github.com/RiotGames/developer-relations/issues
