### ISSUE TITLE
Documentation for rate limiter

### ISSUE THREAD

**Issue by awesomepgm** [pseudonym117/Riot-Watcher#185]
This is more of a question than an issue but, I would like to ask whether or not there is any documentation for the rate limiter. I was wondering more specifically if there was a way to change the rates and if so how do you do so. Also, I would like to ask whether the rate limiter actually does a sleep/wait to prepare for the next request in order to prevent it from giving a 429 error. Thank you in advance.

**Comment by pseudonym117** [comment]
Rate limits are read from the headers directly from riot. There currently is no user-facing control over this, besides writing your own entire rate limiter. 

The rate limiter will sleep before executing the a request if it anticipates a 429 error will be returned.
