### ISSUE TITLE
Would it be more efficient to use requests.Session()?

### ISSUE THREAD

**Issue by hingston** [pseudonym117/Riot-Watcher#187]
Wouldn't it be more efficient to use [`requests.Session()`](https://docs.python-requests.org/en/master/user/advanced/)?

Currently using `requests.get()`: https://github.com/pseudonym117/Riot-Watcher/blob/16659b30898dae9f62cee9ddaa8711469f1d0ddd/src/riotwatcher/_apis/BaseApi.py#L41

**Comment by pseudonym117** [comment]
Yes. fixed now. will be in next release.
