### ISSUE TITLE
Unable to import in python3.4

### ISSUE THREAD

**Issue by TheSpiritof69** [pseudonym117/Riot-Watcher#19]
Hello,

I can't seem to get this package to import correctly.

Whenever I try `from riotwatcher import RiotWatcher` I get an "Cannot import name RiotWatcher" error.

I tried installing the package via pip as well as manually via setup.py.

Do you have any ideas?

**Comment by Murkantilism** [comment]
Do you have an __init__.py file?

**Comment by TheSpiritof69** [comment]
In the riotwatcher package? Yes.

It's the recent 1.2.5

**Comment by Murkantilism** [comment]
Oh if your riotwatcher dir is in the same dir as the file you're trying to
import into I believe it should be:

from RiotWatcher.riotwatcher import RiotWatcher

**Comment by TheSpiritof69** [comment]
No, it's installed into the site-packages of my python environment :/

**Comment by Murkantilism** [comment]
I doubt we'll be able to help you without more specifics then, what OS are you using?

[This SO thread](http://stackoverflow.com/questions/2351919/python-error-importerror-cannot-import-name-akismet) has basic troubleshooting for this problem that you should attempt.

**Comment by Murkantilism** [comment]
As I'm sure you know it's a real bad idea to use import *, makes tracing namespace issues and other bugs damn near impossible.

**Comment by pseudonym117** [comment]
There's a chance this is just my __init__.py is just wrong, test with " ...
Import *". If that works then the there's something wrong with the package
.

Yeah import * is bad usually . But just to check if it's your environment
or the code, try it

**Comment by TheSpiritof69** [comment]
With import * it works, I have to adress the Class RiotWatcher explicitly via riotwatcher.Riotwatcher afterwards..so I suppose it's the package...

**Comment by kihashi** [comment]
Was this fixed in #20 ?

**Comment by pseudonym117** [comment]
oops, yeah. forgot to close this. mah bad.
