### ISSUE TITLE
Different behaviour between summoner.by_name and official API

### ISSUE THREAD

**Issue by Josde** [pseudonym117/Riot-Watcher#202]
When using summoner.by_name() I get different values for the IDs in riot-watcher compared to the official Riot Games page. The values that riot-watcher gives me are incorrect and lead to errors when searching matches by PUUID, for example.  
When querying user "asdf" in region euw1 through riot-watcher, I get these values:
![image](https://user-images.githubusercontent.com/3825181/147853566-bf5253d3-d8c6-4f04-916a-1d7f630d77c5.png)
Meanwhile, querying the same player from the official riot games API page gives these values, with the correct IDs:  
![image](https://user-images.githubusercontent.com/3825181/147853587-f69c0097-887b-4537-b74f-7023cc40041e.png)
As you can see in the screenshots, even though the name, level and other attributes are correct, every single ID is wrong in riotwatcher. I have no idea on why this is happening even after looking at the module's code.  
riotwatcher version: 3.2.0

**Comment by pseudonym117** [comment]
All ID'S are unique to your api key. Most likely case is that you are using different keys on the web vs with code.

**Comment by Josde** [comment]
Yeah, my bad, that's it. I thought it was an issue with the package because my program used to work before and suddenly I started getting different IDs than what I had in my database, and the ones that I already had didn't work in the developer page. Didn't know they existed on a per-key base, and every single of my errors came from mixing different keys. Thanks and sorry for raising this issue :)
