### ISSUE TITLE
Error on matchlist_by_account

### ISSUE THREAD

**Issue by ScottCarrara** [pseudonym117/Riot-Watcher#206]
Hello! I was following this example to learn how to use this Library: https://towardsdatascience.com/how-to-use-riot-api-with-python-b93be82dbbd6

But I keep getting this error
![image](https://user-images.githubusercontent.com/18254049/163735823-14028541-24a0-4549-99ca-57d973b74279.png)

I've tried to set to use ApiV4 as showed in the Readme, but I keep getting the same error.
![image](https://user-images.githubusercontent.com/18254049/163735887-1e6e42c6-415e-4a1b-b6e0-406e878c834b.png)

Did anyone get this error too? How do I solve it?

Thanks!

**Comment by 6weaver** [comment]
Hi

You can only call the matchlist from puuid https://i.imgur.com/D9Qtjio.png

I'm using it as such : "matchhistory=lol_watcher.match.matchlist_by_puuid(my_region, my_puuid,count=99)" 
with my_puuid being a string containing my puuid. good luck
