### ISSUE TITLE
API back killParticipation is wrong

### ISSUE THREAD

**Issue by loreliu** [pseudonym117/Riot-Watcher#209]
In this [game](https://www.op.gg/summoners/kr/waiga/matches/KgLASefpaoA1rGuvOOod1NSWWMOdNzX1edOgBa8fqhE%3D/1652164060000), kalista's kill Participation(K+A / total kills of team) is 0.43(6+9 / 35) but the api back 'killParticipation': 0.29411764705882354 which is  K+A / total kills of enemy team(6+9 / 51).
![image](https://user-images.githubusercontent.com/50559255/167615047-03ca0b24-bd88-449d-b09d-fb168946cae8.png)

![image](https://user-images.githubusercontent.com/50559255/167615283-3d45c32b-6561-44d6-b90e-eca221aea668.png)

**Comment by loreliu** [comment]
In this [game](https://www.op.gg/summoners/kr/waiga/matches/KgLASefpaoA1rGuvOOod1NSWWMOdNzX1edOgBa8fqhE%3D/1652164060000), kalista's kill Participation(K+A / total kills of team) is 0.43(6+9 / 35) but the api back 'killParticipation': 0.29411764705882354 which is  K+A / total kills of enemy team(6+9 / 51).
![image](https://user-images.githubusercontent.com/50559255/167615047-03ca0b24-bd88-449d-b09d-fb168946cae8.png)

![image](https://user-images.githubusercontent.com/50559255/167614847-0e5e1901-c7cd-4fd4-ad93-d9b92678d4ab.png)

**Comment by pseudonym117** [comment]
`riotwatcher` has no control over this. 

Report here if you think it is still an issues: https://github.com/RiotGames/developer-relations/issues
