### ISSUE TITLE
Does not have Urf Mode Api.

### ISSUE THREAD

**Issue by Charleezy** [pseudonym117/Riot-Watcher#21]
I can't figure out your code enough to add one myself. I keep getting simple python errors too.

**Comment by Murkantilism** [comment]
Does the official API have an end point for URF mode? I don't see one in the documentation.

**Comment by Charleezy** [comment]
Yes. It's for the Riot API Challenge
https://developer.riotgames.com/api/methods

**Comment by pseudonym117** [comment]
yeah sorry, this was a temporary api so i didnt bother with it. There was no use in implementing it if its going to have to be removed 2 weeks later.
