### ISSUE TITLE
Package is not pep561 compliant

### ISSUE THREAD

**Issue by ughstudios** [pseudonym117/Riot-Watcher#223]
https://peps.python.org/pep-0561/

Add a types-riot-watcher package, or a py.typed file.

**Comment by pseudonym117** [comment]
Types exist on all deterministic values.

The design choice of allowing the `deserializer` init parameter allows users to change the return types of all API endpoint calls.

Maybe there is a way with generics to make this work at compile time, but it is non-trivial. As of now, all undocumented API endpoint return types are `dict`. If an easy way to handle this via generics exists, I can update, but currently I do not see a way to support while both:

- keeping support for user-defined deserialization
- Ensuring return types are factually correct when user-defined deserialization is used.
