### ISSUE TITLE
Can't request for specific match type.

### ISSUE THREAD

**Issue by pafi-code** [pseudonym117/Riot-Watcher#224]
There is a small change required in [MatchApiV5.py](https://github.com/pseudonym117/Riot-Watcher/blob/0c5249be2d24792bc2b618db54b3f351a99ab83b/src/riotwatcher/_apis/league_of_legends/MatchApiV5.py#L81).

The `type` argument should be changed to `queueType` following [riot docs](https://developer.riotgames.com/docs/lol)

**Comment by Paulie-Aditya** [comment]
can fix this, could I get this assigned?

**Comment by pseudonym117** [comment]
As per https://developer.riotgames.com/apis#match-v5/GET_getMatchIdsByPUUID, the arguments are `queue` and `type`, not `queueType`.

Closing issue. If the official docs are incorrect, feel free to reopen.

**Comment by pafi-code** [comment]
So from the riot docs see the screenshot:
![image](https://github.com/pseudonym117/Riot-Watcher/assets/69895152/620db46d-71c9-4add-9c37-6fedec54ed89)

I assumed the `type` keyword is supposed to be used for this?! Or did I misunderstand its usage?

**Comment by BlossomiShymae** [comment]
I believe that documentation is referring to the queue and `queueType` field for the League-v4 endpoint e.g `RANKED_SOLO_5x5`.

The argument `type` is referring to the values `normal`, `ranked`, etc. if I'm not mistaken.
