### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by fernandojunior** [pseudonym117/Riot-Watcher#29]
Syntax error when try to execute following (Readme):

``` py
my_mastery_pages = w.get_mastery_pages([me['id', ])[str(me['id'])]
```

Use this:

``` py
my_mastery_pages = w.get_mastery_pages([me['id']])[str(me['id'])]
```

**Comment by pseudonym117** [comment]
I'm extremely late here, but the code there works for me. are you using python3 or python2?

**Comment by dexter136** [comment]
I also got a syntax error using python3.5.0b4.
fernandojunior's change fixed the issue for me as well.

**Comment by thigobr83** [comment]
fernandojunior

The problem is not where you mentioned, missing one] before the parentheses

`my_mastery_pages = w.get_mastery_pages([me['id', ])[str(me['id'])]`

Use this

`my_mastery_pages = w.get_mastery_pages([me['id', ]**]**)[str(me['id'])]`
