### ISSUE TITLE
You exposed your Riot API Key

### ISSUE THREAD

**Issue by gnozell** [pseudonym117/Riot-Watcher#31]
In tests.py you set key = '5cf65626-43f1-4919-aade-47bba8c847b9' which is your League of Legends API Key. You should probably change it like in your README.rst to 'your-api-key' and also reset your actual key.

Reasons why you should not give out your key listed here: https://developer.riotgames.com/docs/credentials-security

**Comment by pseudonym117** [comment]
So of a bitch I always forget to undo my changes to that tests file. Thanks for reporting, will change
