### ISSUE TITLE
Add unittests and travis.yml

### ISSUE THREAD

**Issue by cdvv7788** [pseudonym117/Riot-Watcher#32]
http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables for the api key.

**Comment by cdvv7788** [comment]
http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings Would be easier to setup.

**Comment by cdvv7788** [comment]
Created a pull request for this https://github.com/pseudonym117/Riot-Watcher/pull/33

**Comment by pseudonym117** [comment]
suuuuuuuuper late, but i managed to get this actually set up. not through this though, and without environment variables.
