### ISSUE TITLE
matchhistory-v2.2 will be deprecated on 09/22/15.

### ISSUE THREAD

**Issue by christophM** [pseudonym117/Riot-Watcher#39]
Just wanted to let you know that the matchhistory-v2.2 API endpoint will deprecated on 09/22/15, in case you did not know yet. Not sure if they will remove it completely on this date. There is just an innocent note saying "This API will be deprecated on 09/22/15." in https://developer.riotgames.com/api/methods#!/1025/3479

![bildschirmfoto 2015-09-17 um 20 19 43](https://cloud.githubusercontent.com/assets/1632100/9942083/7fb13522-5d79-11e5-8827-3af1c502e5b4.png)

**Comment by pseudonym117** [comment]
The match list api replacing it had been added as of pull request #30. Will remove outdated apis when they officially no longer work.
