### ISSUE TITLE
Match History is deprecated

### ISSUE THREAD

**Issue by fernandojunior** [pseudonym117/Riot-Watcher#40]
Match History (matchhistory) API is deprecated. It was replaced by [matchlist](https://developer.riotgames.com/api/methods#!/1033/3539).

[See](https://developer.riotgames.com/api/methods).

Request:
/api/lol/{region}/v2.2/matchlist/by-summoner/{summonerId}

**Comment by pseudonym117** [comment]
fixed in commit b40b898
