### ISSUE TITLE
pypi downloads 1.2.5; should download 1.3.1

### ISSUE THREAD

**Issue by MiguelAngelDiaz** [pseudonym117/Riot-Watcher#41]
Not sure what it takes to download 1.3.1 from pypi.

I already upgrade pip using ```pip install --upgrade pip``` and even tried``` pip install riotwatcher==1.3```  but no luck.

As of October 30, 2015, it's not getting 1.3.1 nor 1.3; it is showing patch notes for 1.3, though. 

Here's the link https://pypi.python.org/pypi/riotwatcher/1.3

**Comment by pseudonym117** [comment]
Oops. Forgot to update on pypi. Will update later tonight.

**Comment by pseudonym117** [comment]
well im extremely late in doing this, mostly because i forgot after a 3 hour drive. but now this is fixed.
