### ISSUE TITLE
New constants for season 6

### ISSUE THREAD

**Issue by chenwardT** [pseudonym117/Riot-Watcher#52]
The first one I've discovered is `TEAM_BUILDER_DRAFT_RANKED_5x5` as a possible value for queue types. This is a valid value for the `rankedQueues` param of Riot's API. It also appears as a value in Match and MatchList responses.

There is also `TEAM_BUILDER_DRAFT_UNRANKED_5x5`. See https://developer.riotgames.com/docs/game-constants

As a side note, it appears that sending rankedQueues=TEAM_BUILDER_DRAFT_RANKED_5x5 to the matchlist endpoint results in a response containing ranked solo, 5s and dynamic queue matches.

I don't use the constants from riotwatcher, but if I feel I've found all the changes (these 2 may very well be it) I will submit a PR.

**Comment by pseudonym117** [comment]
constants are no longer provided by riotwatcher, as i clearly have not been quick enough in providing updates to keep them up to date at all.
