### ISSUE TITLE
Accept iterable of params for args that allow multiple values?

### ISSUE THREAD

**Issue by chenwardT** [pseudonym117/Riot-Watcher#53]
How do you feel about being able to do:

```
rw = RiotWatcher('api-key')
rw.get_match_list(summoner_id=123456,
                  region='na',
                  ranked_queues=('RANKED_SOLO_5x5', 'TEAM_BUILDER_DRAFT_RANKED_5x5'))
# returns match list dict containing both solo queue and dynamic queue matches
```

vs what is now done by:

```
rw = RiotWatcher('api-key')
rw.get_match_list(summoner_id=123456,
                  region='na',
                  ranked_queues='RANKED_SOLO_5x5,TEAM_BUILDER_DRAFT_RANKED_5x5')
```

Right now, using the former, unsupported, syntax results in just the first value being used, which is a bit misleading.

This could break some users' code, and would warrant changing how multiple values are worked with in more of riotwatcher's API than just `get_match_list`, but I think it'd be a good change. Support could be added to preserve the old functionality while enabling the new and then we emit some deprecation warning if, e.g. a comma is detected in a param for an arg that accepts multiple values.

**Comment by chenwardT** [comment]
BTW, I would take responsibility for adding this, j/w if it'd be something that would make it in.

**Comment by pseudonym117** [comment]
as long as both formats are supported (no deprecation warning, i think either format is acceptable), then that should be totally fine. whenever you get around to changing it submit the pull request and i will merge it

**Comment by chenwardT** [comment]
Fixed in https://github.com/pseudonym117/Riot-Watcher/pull/54
