### ISSUE TITLE
Handle RateLimits inside 

### ISSUE THREAD

**Issue by dmgciubotaru** [pseudonym117/Riot-Watcher#58]
would be nice if RateLimit.request_available have a "wait" parameter to sleep till next request can be made

**Comment by fab0l1n** [comment]
while not Riot-Watcher.can_make_request():
        pass

Just do it yourself.

**Comment by dmgciubotaru** [comment]
But a time.sleep is better than a while pass

**Comment by fab0l1n** [comment]
You can put a time.sleep in there, if you want to:

    while not Riot-Watcher.can_make_request():
        time.sleep(5)

**Comment by pseudonym117** [comment]
now done by default as of 3844d16. can be deconfigured by user if desired (information will be added to readme soon tm)
