### ISSUE TITLE
get_league_entry() is returning the wrong player's info

### ISSUE THREAD

**Issue by cameronstowell** [pseudonym117/Riot-Watcher#62]
When I try to call a summoner's league entry using their ID it's returning information for the completely wrong player.

**Comment by taymourheikal** [comment]
Bump.
Same issue.

**Comment by fab0l1n** [comment]
make sure your ID is same is shown [here](http://privacy.riotgames.com/en_US/)

**Comment by taymourheikal** [comment]
@fab0l1n  I save my ID as a variable after using the get_summoner() function, then I use that variable as input for get_league(). Then I check if `myid in ids`, which returns False. So it shouldn't really matter who's ID it is; the check should always return true.

**Comment by asishm** [comment]
@taymourheikal The reason being that the id that you get from `get_summoner()` is an integer while in `get_league()` it returns a string which is why you get a `False` if you check `if str(myid) in ids` you would probably get True.

**Comment by taymourheikal** [comment]
@asishm Unfortunately, that's not the problem either. The tier returned when I `get_league()` is Silver - Anivia's Spellbeakers; I'm in Bronze - Xin Zhao's Outriders.

(Yes, I'm a noob in Bronze)

**Comment by asishm** [comment]
If you don't mind, could you share your ID that get_summoner() returns?

**Comment by taymourheikal** [comment]
Not at all:
65593898

**Comment by asishm** [comment]
I can't seem to reproduce it

```py
leagues = watcher.get_league_entry(['65593898']) # watcher = RiotWatcher() instance
data = leagues['65593898'][0] # there's only one league
```

This gives me 
```py
>>> data['name']
"Xin Zhao's Outriders"
>>> data['tier']
'BRONZE'
>>> data['queue']
'RANKED_SOLO_5x5'
>>> data['participantId']
'65593898'
>>> any('65593898' in player['playerOrTeamId'] for player in data['entries'])
True
```

**Comment by fab0l1n** [comment]
Same here.

> 'https://na.api.pvp.net/api/lol/na/v2.5/league/by-summoner/65593898?api_key=<>'

does return the [correct information](http://textuploader.com/d177x) for me.

try printing your response and compare that.  You can also just open the URL in your browser.

**Comment by taymourheikal** [comment]
That's weird:
```
from riotwatcher import RiotWatcher
import requests
api = RiotWatcher(<api>)
myid = str(api.get_summoner('Timkacious')['id'])
myleague = api.get_league(myid)
data = myleague['65593898'][0]
KeyError: '65593898'

myleague = api.get_league('65593898')
KeyError: '65593898'
```

**Comment by asishm** [comment]
@taymourheikal 

`get_league()` and `get_league_entry()` take in a list of summoner ids. You're passing it a string which (since strings are iterable) the code assumes is a list of single digit ids which is why if you look at the results that you get - you'll probably notice some single digit ids in there

Pass in `'65593898'` as a list `['65593898']` to those methods and it should work

**Comment by taymourheikal** [comment]
I'm a muppet.

Thanks guys! 👍

**Comment by cameronstowell** [comment]
Thanks - just got back to this and saw this.
