### ISSUE TITLE
Update the Pypi package

### ISSUE THREAD

**Issue by FunkySayu** [pseudonym117/Riot-Watcher#64]
Would it be possible to update it? It is still impossible to install this library on Python 3.

EDIT: Actual pip command: `pip3.5 install --user riotwatcher`

**Comment by fab0l1n** [comment]
It's a single file, so if pip doesn't work you can just copy-paste it into your directory.

**Comment by pseudonym117** [comment]
fixed as of 3844d16 - bit late, but at least its fixed
