### ISSUE TITLE
Free to play request returns all champions

### ISSUE THREAD

**Issue by danijoo** [pseudonym117/Riot-Watcher#68]
Querying for free to play champions seem to return all champions because the url is wrongly formatted:

```
riotwatcher.get_all_champions(settings.STATIC_DATA_REGION, free_to_play=True)
print(len(response['champions'])) # => 134
```

The reason is that the parsed url looks like this:
```
/api/lol/NA/v1.2/champion/?api_key=SECRET&freeToPlay=True 
````
but should actually look like this for additional arguments being accepted by riot (remove / before params):
```
/api/lol/NA/v1.2/champion?api_key=SECRET&freeToPlay=True 
````

**Comment by pseudonym117** [comment]
seems to be fixed as of 3844d16 (version 2.0.1)
