### ISSUE TITLE
Optional Query Parameters

### ISSUE THREAD

**Issue by wanqizhu** [pseudonym117/Riot-Watcher#77]
e.g. support optional forAccountId / forPlatformId keyword argument when calling match.by_id()

-- see https://developer.riotgames.com/api-methods/#match-v3/GET_getMatch

We should be able to call something like

watcher.match.by_id(region, match_id, forAccountId=None, forPlatformId=None)

**Comment by pseudonym117** [comment]
new policy on normal games rendered these parameters unnecessary. no longer are used by the API
