### ISSUE TITLE
Variable types in the documentation

### ISSUE THREAD

**Issue by yuriescl** [pseudonym117/Riot-Watcher#80]
In this page of the documentation: 
[StaticDataApiV3](http://riot-watcher.readthedocs.io/en/latest/riotwatcher/StaticDataApiV3.html#riotwatcher._apis.StaticDataApiV3)

In the function `champions(region, locale=None, version=None, tags=None, data_by_id=None)`, the parameter `data_by_id` is documented as having the type `bool`. I tested and by using `data_by_id=True` I got a Bad Request error. Changed it to `data_by_id="true"` and it worked. This means that the wrapper is not converting from True to "true" and instead it's using the value directly into the URL. So in the URL it's becoming `dataById=True`.

Is RiotWatcher using the values directly in the URL instead of converting from Python types to JSON types?

**Comment by pseudonym117** [comment]
Yep. values are used directly at the moment. will change this, you should still provide booleans where the documentation says to, the wrapper should just correct this.

**Comment by pseudonym117** [comment]
fixed in commit 65d648f
