### ISSUE TITLE
AttributeError when trying to get using leagues_by_summoner

### ISSUE THREAD

**Issue by angelotc** [pseudonym117/Riot-Watcher#81]
`>>> me`
`{'id': 50156526, 'accountId': 212758343, 'name': 'l am Anjo', 'profileIconId': 973, 'revisionDate': 1502660431000, 'summonerLevel': 30}`
`>>> my_region = 'na1'`
`>>> my_ranked_stats = watcher.league.leagues_by_summoner(my_region, me['id'])`
`Traceback (most recent call last):`
`  File "<pyshell#66>", line 1, in <module>`
`    my_ranked_stats = watcher.league.leagues_by_summoner(my_region, me['id'])`
`AttributeError: 'LeagueApiV3' object has no attribute 'leagues_by_summoner'`
`>>> `

**Comment by pseudonym117** [comment]
method is watcher.league.by_summoner(...). use that instead.
