### ISSUE TITLE
Incorrect URL for League V3 get positions for summoner

### ISSUE THREAD

**Issue by blakehurlburt** [pseudonym117/Riot-Watcher#84]
The URL given for this is _lol/league/v3/**leagues**/by-summoner/`_, it should be _lol/league/v3/**positions**/by-summoner/_

**Comment by blakehurlburt** [comment]
Edit: I'm dumb, the real issue is that the "leagues" API doesn't exist anymore and should be removed, the "positions" one works just fine.

**Comment by Aw3same** [comment]
Same issue. The example code in README doesn't work. (Error 403 Forbidden)

**Comment by darrendlin** [comment]
It looks like the `lol/league/v3/leagues/by-summoner/` endpoint doesn't exist anymore - I can just get rid of it and make a PR? @pseudonym117

**Comment by pseudonym117** [comment]
fixed completely with 6fc8799
