### ISSUE TITLE
watcher.match.matchlist_by_account_recent broken

### ISSUE THREAD

**Issue by riceluxs1t** [pseudonym117/Riot-Watcher#88]
Hi,

the "watcher.match.matchlist_by_account_recent" api is broken; it seems Riot has changed its API URL routing. You can reproduce this by running the "full_test_RiotWatcher.py" unittest.

**Comment by cnguy** [comment]
iirc that endpoint was removed by Riot because its functionality is covered by the regular matchlist endpoint (where beginIndex is 0 and endIndex is 20)

**Comment by riceluxs1t** [comment]
I believe so too. I say simply deprecate this "matchlist_by_account_recent" method.

**Comment by pseudonym117** [comment]
Yes, this seems to be removed by Riot and I haven't removed it yet.

Which option would be better to address this?

- Remove "matchlist_by_account_recent" method entirely
- Emulate the functionality of recent by simply making this function call "matchlist_by_account" and querying 20 matches

I am leaning towards removing the method entirely, but if other people would prefer the old method exist as a helper, I am not opposed to that either.

**Comment by riceluxs1t** [comment]
I say remove it entirely. It just creates confusion for a newcomer (like myself).

 The latter option would help maintain application code that may use "matchlist_by_account_recent" method. But any serious user should have figured out the method was broken a long time ago and most likely migrated to "matchlist_by_account".

**Comment by pseudonym117** [comment]
Then it seems in that case, I will remove the method. Will try to address later tonight...

**Comment by pseudonym117** [comment]
fixed in commit 22cb347
